#!/bin/bash

set -eux

HG_BRANCH="${HG_BRANCH-trunk}"
GIT_BRANCH="${GIT_BRANCH-master}"
GIT_USER="${GIT_USER-citrix-openstack}"
BUILD_HG="${BUILD_HG-http://hg/openstack/$HG_BRANCH/build.hg}"

rootdir="$1"
build_number="$2"

build_hg="$rootdir/build.hg"
thisdir=$(dirname $(readlink -f "$0"))
subdir=$(($build_number / 1000))

env

export USER="${USER-jenkins}"

mkdir -p "$rootdir"

(cd "$thisdir"
 git pull)

if [ -e "$build_hg" ]
then
    cd "$build_hg"
    hg pull && hg update -C || true
else
    cd "$rootdir"
    hg clone "$BUILD_HG"
    cd "$build_hg"
fi

export USE_GIT=true
export GIT_BRANCH
export GIT_USER
set +ex
BUILD_SUFFIX=${SITE-x} \
  GLOBAL_CACHE_DIRS="/openstack_build_cache /usr/groups/cache" \
  make os-vpx-manifest
result=$?
set -ex

if [ $result -eq 0 ]
then
  now=$(date -u "+%Y-%m-%d %H:%M:%SZ")
  mkdir -p "$thisdir/$subdir"
  cp obj/manifest "$thisdir/$subdir/$build_number.manifest"
  cat >"$thisdir/$subdir/$build_number.meta" <<EOF
Build number: $build_number
Branch: $GIT_BRANCH
Date: $now
Manifest: $subdir/$build_number.manifest
EOF
  cd "$thisdir"
  git add "$subdir/$build_number.manifest"
  git add "$subdir/$build_number.meta"
  git commit -m "Build $build_number.  Branch: $GIT_BRANCH."
  git push
fi

exit $result
